version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps:/app
      - /app/node_modules
      - ./data:/app/data # Mount data directory for DB and images
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
