services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    volumes:
      - ./apps/web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    # Add this to ensure the container exits gracefully on Ctrl+C
    init: true