name: CD

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - '.github/workflows/cd.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build and push container image
        working-directory: ./apps/web
        run: |
          IMAGE_ID=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/shanari-gemini/app
          docker build -t $IMAGE_ID:${{ github.sha }} -t $IMAGE_ID:latest .
          docker push $IMAGE_ID:${{ github.sha }}
          docker push $IMAGE_ID:latest
