name: CD

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - '.github/workflows/cd.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build and push container image
        id: build-push
        working-directory: ./apps/web
        run: |
          IMAGE_ID=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/shanari-gemini/app
          docker build -t $IMAGE_ID:${{ github.sha }} -t $IMAGE_ID:latest .
          docker push $IMAGE_ID:${{ github.sha }}
          docker push $IMAGE_ID:latest
          echo "IMAGE_URL=$IMAGE_ID:${{ github.sha }}" >> $GITHUB_OUTPUT

      # - name: Deploy to Cloud Run
      #   # This step is commented out until Infra-001 is complete and the Cloud Run service exists.
      #   run: |
      #     gcloud run deploy shanari-gemini-app \
      #       --image ${{ steps.build-push.outputs.IMAGE_URL }} \
      #       --region ${{ secrets.GCP_REGION }} \
      #       --platform managed \
      #       --allow-unauthenticated \
      #       --set-env-vars="GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }},ADMIN_EMAIL_LIST=${{ secrets.ADMIN_EMAIL_LIST }}"
